version: '3'

services:
  #PHP Service
  corteva_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: corteva/php
    container_name: corteva_app
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh:ro
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - corteva-app-network

  #Nginx Service
  corteva_webserver:
    image: nginx:alpine
    container_name: corteva_webserver
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - corteva-app-network
  
  # SqlServer Service
  corteva_db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: corteva_db
    tty: true
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - cortevadbdata:/var/opt/mssql/
      - ./data:/var/opt/appdata/
    networks:
      - corteva-app-network

#Docker Networks
networks:
  corteva-app-network:
    driver: bridge

# Volumes
volumes:
  cortevadbdata:
    driver: local
